(function (Blockly) {
  Blockly.Msg = Blockly.Msg || {};
  Object.assign(Blockly.Msg, {
    // Basic UI
    "BKY_HELP_HINT": "Right click for help",
    "BKY_SAVE_SUCCESS": "Saved successfully!",
    "BKY_NEW_VARIABLE_HINT": "Enter variable name(s), comma separated.\nNote: Name cannot start with a number or contain special characters except underscores.",

    // Category Colours (Hex Palette)
    "COLOUR_STRUCTURE": "#585858",
    "COLOUR_LOGIC": "#b198de",
    "COLOUR_LOOPS": "#7fcd81",
    "COLOUR_MATH": "#5C68A6",
    "COLOUR_TEXT": "#6a8871",
    "COLOUR_TYPES": "#d1972b",
    "COLOUR_VARIABLES": "#ef9a9a",
    "COLOUR_FUNCTIONS": "#d22f73",
    "COLOUR_IO": "#34495e",
    "COLOUR_TIME": "#68a2a3",
    "COLOUR_CODING": "#585858",
    "COLOUR_AI": "#FF661A",
    "COLOUR_AI_BASIC": "#FF661A",
    "COLOUR_AI_DRAW": "#c2bc07",
    "COLOUR_AI_HAND": "#5bd211",
    "COLOUR_AI_FACE": "#01ad9c",
    "COLOUR_AI_POSE": "#1226a7",
    "COLOUR_HARDWARE": "#5c55a0",
    "COLOUR_MCU_CAMERA": "#db00ab",
    "COLOUR_HUSKYLENS": "#1f5a71",
    "COLOUR_MCU_CAR": "#ee5b56",
    "COLOUR_MCU_CAR_MOTOR": "#ee5b56",
    "COLOUR_MCU_CAR_SERVO": "#d40051",
    "COLOUR_MCU_CAR_MUSIC": "#de57ad",
    "COLOUR_MCU_CAR_LED": "#544eca",
    "COLOUR_MCU_CAR_SENSOR": "#b1b100",
    "COLOUR_MCU_CAR_BUTTON": "#0c8b03",

    // Category Names
    "CAT_SEARCH": "Search",
    "CAT_STRUCTURE": "Structure",
    "CAT_IO": "IO",
    "CAT_TIME": "Time",
    "CAT_LOGIC": "Logic",
    "CAT_LOOPS": "Loops",
    "CAT_MATH": "Math",
    "CAT_TEXT": "Text",
    "CAT_TYPES": "Types",
    "CAT_CODING": "Coding",
    "CAT_VARIABLES": "Variables",
    "CAT_FUNCTIONS": "Functions",
    "CAT_AI": "AI Vision",
    "CAT_AI_BASIC": "OpenCV Basic",
    "CAT_AI_DRAW": "Drawing",
    "CAT_AI_HAND": "Hand Tracking",
    "CAT_AI_FACE": "Face Mesh",
    "CAT_AI_POSE": "Pose Detection",
    "CAT_HARDWARE": "Hardware",
    "CAT_MCU_CAMERA": "AI Camera",
    "CAT_HUSKYLENS": "HuskyLens",
    "CAT_MCU_CAR": "πCar / Motor",

    // Types Group Labels
    "TYPE_LBL_DEF": "Definitions",
    "TYPE_LBL_CAST": "Casting & Type Check",
    "TYPE_LBL_OPS": "General Access",
    "TYPE_LBL_METHODS": "Advanced Methods",
    "TYPE_LBL_SORT": "Sorting",

    // Toolbar & UI
    "TLB_NEW": "New Project",
    "TLB_OPEN": "Open Project",
    "TLB_SAVE": "Save Project",
    "TLB_SAVE_AS": "Save As...",
    "TLB_SETTINGS": "Settings",
    "TLB_SETTINGS_PYTHON_PATH": "Set Python Path",
    "TLB_SETTINGS_SCROLL_OPTIONS": "Enable Scroll Options (Restart required)",
    "TLB_SETTINGS_SERIAL_UPLOAD": "Stable Mode (Serial Upload Only)",
    "TLB_SETTINGS_FIRMWARE_GROUP": "Firmware Settings",
    "TLB_SETTINGS_SETUP_STABLE": "Lock USB Disk (Stable Mode)",
    "TLB_SETTINGS_ERASE_FS": "Reset USB Disk (Erase All Files)",
    "TLB_SETTINGS_RESET_FIRMWARE": "Reset Firmware (Flash UF2)",

    "TLB_RUN": "Run Program",
    "TLB_RUN_PC": "Run PC Program",
    "TLB_RUN_MCU": "Upload to MCU",
    "TLB_UPDATE": "Check for Updates",
    "TLB_STOP": "Close",
    "TLB_SERIAL_PORT": "Serial Port",
    "TLB_SERIAL_REFRESH": "Detect Serial Port",
    "TLB_SERIAL_CONNECT": "Connect Serial",
    "TLB_SERIAL_DISCONNECT": "Disconnect Serial",
    "TLB_FILE_NEW": "Untitled Project",
    "TLB_PYTHON_PREVIEW": "Code Preview",
    "TLB_MODE_PC": "💻 Python (PC)",
    "TLB_MODE_MCU": "📟 MicroPython (MCU)",
    "TLB_DIAGNOSE": "Check Python Package Requirements",

    // Environment Diagnosis
    "DIAG_TITLE": "Environment Diagnostic Assistant",
    "DIAG_LOADING": "Detecting Python module status...",
    "DIAG_CHECKING": "Checking...",
    "DIAG_INSTALLED": "● Installed",
    "DIAG_MISSING": "○ Missing",
    "DIAG_INSTALL_BTN": "Install",
    "MSG_CLOSE": "Close",

    // Update messages
    "MSG_UPDATE_LATEST": "Already up to date (%1)",
    "MSG_UPDATE_AVAILABLE": "New version available (%1)",
    "MSG_UPDATE_LATEST_TOOLTIP": "You are using the latest version (%1)",
    "MSG_UPDATE_AVAILABLE_TOOLTIP": "New version available (%1). Click to download.",

    // Dialogs & Messages
    "MSG_SAVE_CONFIRM": "Do you want to save changes to the current project?",
    "MSG_SWITCH_CONFIRM": "Switching modes will clear the workspace and start a new project. Are you sure you want to switch to %1 mode?",
    "MSG_SAVE": "Save",
    "MSG_DONT_SAVE": "Don't Save",
    "MSG_OK": "OK",
    "MSG_CANCEL": "Cancel",
    "MSG_SELECT_PATH": "Select Path",
    "MSG_SELECT_PORT": "Please select a serial port first!",
    "MSG_PYSERIAL_MISSING": "pyserial module not found. Please run 'pip install pyserial' to enable hardware deployment.",
    "MSG_DEPLOYING_MCU": "Deploying code to MCU (%1)...",
    "MSG_DEPLOY_UPLOADING": "Uploading, do not disconnect USB...",
    "MSG_DEPLOY_COMPLETED": "Upload completed, you can disconnect USB.",
    "MSG_UPDATE_LATEST": "You are already using the latest version.",
    "MSG_PYTHON_NOT_FOUND": "Could not execute Python (Current: %1). Please specify the correct python.exe path.",
    "MSG_PYTHON_UPDATED": "Python path updated: %1",
    "MSG_RECOVER_BACKUP": "Unsaved changes detected. Do you want to recover them?",
    "MSG_RECOVER_IGNORE": "Ignore and start new project",
    "MSG_RESET_FIRMWARE_CONFIRM": "Resetting firmware will clear all content on the MCU. Please ensure the MCU is in BOOTSEL / Flashing mode.\nContinue?",
    "MSG_ASK_CLEAR_CODE": "Do you want to clear the code (code.py) on the MCU after burning?",
    "MSG_SELECT_MCU_MODEL": "Please select your MCU model:",
    "MSG_FIRMWARE_BURN_SUCCESS": "Firmware burned successfully! The MCU will restart.",
    "MSG_FIRMWARE_BURN_FAILED": "Burning failed: ",
    "MSG_RELOAD_TO_APPLY": "Settings saved. Please restart the application to apply changes.",
    "MSG_SETUP_STABLE_CONFIRM": "This will write boot.py to MCU to enable Stable Mode.\n\n[Effect]: Windows will become Read-Only for this drive (preventing damage), and Cocoya will upload code via Serial.\n[Escape]: To restore Windows write access later, hold \"GP20 button (Button 1)\" while plugging in the USB cable.\n\nAre you sure you want to continue?",

    // Syntax (Basic)
    "PY_DEF": "def",
    "PY_RETURN": "return",
    "PY_GLOBAL": "global",
    "PY_LOCAL": "local"
  });
})(Blockly);
