(function (Blockly) {
  Blockly.Msg = Blockly.Msg || {};
  Object.assign(Blockly.Msg, {
    // Basic UI
    "BKY_HELP_HINT": "Right click for help",
    "BKY_EXAMPLES_READ_ONLY": "Opening the built-in example was cancelled. Built-in examples are read-only; please reopen and choose \"Copy & Open\" to copy the example to your user workspace.",
    "BKY_SAVE_SUCCESS": "Saved successfully!",
    "BKY_NEW_VARIABLE_HINT": "Enter variable name(s), comma separated.\nNote: Name cannot start with a number or contain special characters except underscores.",

    // Category Colours (Hex Palette)
    "COLOUR_STRUCTURE": "#585858",
    "COLOUR_LOGIC": "#b198de",
    "COLOUR_LOOPS": "#7fcd81",
    "COLOUR_MATH": "#5C68A6",
    "COLOUR_TEXT": "#6a8871",
    "COLOUR_TYPES": "#d1972b",
    "COLOUR_VARIABLES": "#ef9a9a",
    "COLOUR_FUNCTIONS": "#d22f73",
    "COLOUR_IO": "#34495e",
    "COLOUR_TIME": "#68a2a3",
    "COLOUR_CODING": "#585858",
    "COLOUR_AI": "#FF661A",
    "COLOUR_AI_BASIC": "#FF661A",
    "COLOUR_AI_DRAW": "#c2bc07",
    "COLOUR_AI_HAND": "#5bd211",
    "COLOUR_AI_FACE": "#01ad9c",
    "COLOUR_AI_POSE": "#1226a7",
    "COLOUR_HARDWARE": "#5c55a0",
    "COLOUR_MCU_CAMERA": "#db00ab",
    "COLOUR_HUSKYLENS": "#1f5a71",
    "COLOUR_MCU_CAR": "#ee5b56",
    "COLOUR_MCU_CAR_MOTOR": "#ee5b56",
    "COLOUR_MCU_CAR_SERVO": "#bf6bf4",
    "COLOUR_MCU_CAR_MUSIC": "#de57ad",
    "COLOUR_MCU_CAR_LED": "#544eca",
    "COLOUR_MCU_CAR_SENSOR": "#b1b100",
    "COLOUR_MCU_CAR_BUTTON": "#0c8b03",

    "COLOUR_SPIKE": "#d28303",
    "COLOUR_SPIKE_MOTOR": "#ee5b56",
    "COLOUR_SPIKE_MUSIC": "#de57ad",
    "COLOUR_SPIKE_LED": "#544eca",
    "COLOUR_SPIKE_SENSOR": "#b1b100",
    "COLOUR_SPIKE_BUTTON": "#0c8b03",

    // Category Names
    "CAT_SEARCH": "Search",
    "CAT_STRUCTURE": "Structure",
    "CAT_IO": "IO",
    "CAT_TIME": "Time",
    "CAT_LOGIC": "Logic",
    "CAT_LOOPS": "Loops",
    "CAT_MATH": "Math",
    "CAT_TEXT": "Text",
    "CAT_TYPES": "Types",
    "CAT_CODING": "Coding",
    "CAT_VARIABLES": "Variables",
    "CAT_FUNCTIONS": "Functions",
    "CAT_AI": "AI Vision",
    "CAT_AI_BASIC": "OpenCV Basic",
    "CAT_AI_DRAW": "Drawing",
    "CAT_AI_HAND": "Hand Tracking",
    "CAT_AI_FACE": "Face Mesh",
    "CAT_AI_POSE": "Pose Detection",
    "CAT_AI_INFERENCE": "AI Inference",
    "COLOUR_AI_INFERENCE": "#9C27B0",
    "CAT_HARDWARE": "Hardware",
    "CAT_MCU_CAMERA": "AI Camera",
    "CAT_HUSKYLENS": "HuskyLens",
    "CAT_MCU_CAR": "πCar / Motor",
    "CAT_SPIKE": "Lego SPIKE Prime",
    "CAT_SPIKE_INIT": "Init",
    "CAT_SPIKE_MOTOR": "Motors",
    "CAT_SPIKE_COLOR": "Color Sensor",
    "CAT_SPIKE_DISTANCE": "Distance Sensor",
    "CAT_SPIKE_FORCE": "Force Sensor",
    "CAT_SPIKE_HUB": "Hub Built-in",

    // Types Group Labels
    "TYPE_LBL_DEF": "Definitions",
    "TYPE_LBL_CAST": "Casting & Type Check",
    "TYPE_LBL_OPS": "General Access",
    "TYPE_LBL_METHODS": "Advanced Methods",
    "TYPE_LBL_SORT": "Sorting",

    // Toolbar & UI
    "TLB_EXAMPLES": "Open Examples",
    "TLB_NEW": "New Project",
    "TLB_NEW_VSIX": "New Project",
    "TLB_NEW_TAURI": "New Project in This Window",
    "TLB_NEW_WINDOW": "New Window",
    "TLB_OPEN": "Open Project",
    "TLB_SAVE": "Save Project",
    "TLB_SAVE_AS": "Save As...",
    "TLB_SETTINGS": "Settings",
    "TLB_SETTINGS_PYTHON_ENV": "Python Environment (Path & Modules)",
    "TLB_SETTINGS_SERIAL_UPLOAD": "Stable Mode (Serial Upload Only)",
    "TLB_SETTINGS_FIRMWARE_GROUP": "Firmware Settings",
    "TLB_SETTINGS_SETUP_STABLE": "Lock USB Disk (Stable Mode)",
    "TLB_SETTINGS_ERASE_FS": "Deep Repair (Clear MCU Files)",
    "TLB_SETTINGS_ERASE_FS_TOOLTIP": "Stops dead loops and clears internal MCU files. Use when code freezes or to reset for a new user.",
    "TLB_SETTINGS_RESET_FIRMWARE": "Reset Firmware (Flash UF2)",

    "TLB_RUN": "Run Program",
    "TLB_RUN_PC": "Run PC Program",
    "TLB_RUN_MCU": "Upload to MCU",
    "TLB_UPDATE": "Check for Updates",
    "TLB_STOP": "Close Editor",
    "TLB_STOP_PROGRAM": "Stop Program",
    "TLB_CLOSE_EDITOR": "Close Editor",
    "TLB_TERMINAL": "Toggle Terminal",
    "TLB_TOGGLE_CODE": "Toggle Code Preview",
    "TLB_PAUSE_SCROLL": "Pause Auto-scroll",
    "TLB_SERIAL_PORT": "Serial Port",
    "TLB_SERIAL_REFRESH": "Detect Board",
    "TLB_SERIAL_MONITOR": "Serial Monitor (click to open / click again to stop)",
    "TLB_SERIAL_CONNECT": "Connect Serial",
    "TLB_SERIAL_DISCONNECT": "Disconnect Serial",
    "TLB_FILE_NEW": "Untitled Project",
    "TLB_PYTHON_PREVIEW": "Code Preview",
    "TLB_MODE_PC": "💻 Python (PC)",
    "TLB_MODE_MCU": "📟 MicroPython (MCU)",
    "TLB_BACK_HOME": "Back to Home",
    "BKY_STARTUP_NEW": "New Project",
    "BKY_STARTUP_OPEN": "Open Project",
    "BKY_STARTUP_EXAMPLES": "Open Examples",
    "BKY_STARTUP_SETTINGS": "⚙ Quick Settings",
    "BKY_STARTUP_LANG": "Language",
    "BKY_STARTUP_THEME": "Theme",
    "BKY_THEME_AUTO": "Auto (System)",
    "BKY_THEME_LIGHT": "Light",
    "BKY_THEME_DARK": "Dark",
    "BKY_THEME_CANDY": "🍭 Candy Pop",
    "BKY_STARTUP_PYTHON_ENV": "Set Up Python Environment",
    "TLB_AI_MENU": "AI Features",
    "TLB_AI_DATASET_MANAGER": "Dataset Manager",
    "TLB_AI_TRAINING_RESULT": "Training Results",
    "TLB_NO_PORT": "(No Port)",
    "TLB_SERIAL_PLACEHOLDER": "(No Port)",
    "TLB_TERMINAL_TITLE": "TERMINAL",
    "TLB_TOGGLE_TERMINAL": "Toggle Terminal Panel",
    "TLB_COPY_TERMINAL": "Copy All Terminal Text",
    "TLB_FONT_SIZE_TERMINAL": "Terminal Font Size",
    "TLB_FONT_SIZE_CODE": "Code Font Size",
    "TLB_DRAG_RESIZE_HEIGHT": "Drag to resize height",
    "TLB_CLEAR_CONSOLE": "Clear Console",
    "TLB_CLOSE_PANEL": "Close Panel",
    "TLB_DRAG_RESIZE": "Drag to resize",
    "TLB_COPY_CODE": "Copy Code",
    "TLB_INDENT": "Indent:",
    "TLB_INDENT_2": "2 Spaces",
    "TLB_INDENT_4": "4 Spaces",
    "TLB_SELECT_OPTION": "Select Option",
    "MSG_SAVE_CONFIRM_DETAIL": "Changes you make will be lost if not saved.",
    "MSG_NEW_PROJECT_SAVED": "Original project saved. Next, choose the location and filename for the new %1 project.",
    "MSG_SAME_AS_CURRENT": "Cannot save to the current project file location. Please choose a different filename or location.",
    "MSG_SAME_AS_CURRENT_ABORT": "Multiple attempts hit the current project file location. Operation aborted.",
    "TITLE_NEW_PROJECT": "New Project: Choose Save Location",

    // Environment Diagnosis (Python Environment: path + modules)
    "DIAG_TITLE": "Python Environment Setup",
    "DIAG_LOADING": "Detecting Python module status...",
    "DIAG_CHECKING": "Checking...",
    "DIAG_INSTALLED": "● Installed",
    "DIAG_MISSING": "○ Missing",
    "DIAG_INSTALL_BTN": "Install",
    "DIAG_PYTHON_PATH": "Python Path",
    "DIAG_PATH_SELECT": "Browse...",
    "DIAG_INSTALLING": "Installing...",
    "DIAG_INSTALL_FAILED": "✗ Install failed (exit %1)",
    "DIAG_RETRY": "Retry",
    "DIAG_STOP_INSTALL": "Stop install",
    "DIAG_STOP_INSTALL_HINT": "Stop install (this package may need to be reinstalled)",
    "DIAG_PROGRESS_BAR": "Installing %1/%2: %3 (%4s elapsed)",
    "DIAG_PROGRESS_ABORTING": "Stopping install...",
    "DIAG_INSTALL_LOG_SHOW": "▸ Show detailed install output",
    "DIAG_INSTALL_LOG_HIDE": "▾ Hide detailed install output",
    "DIAG_INSTALL_ALL": "Install all missing (%1)",
    "DIAG_INSTALL_ALL_CONFIRM": "Will install %1 missing package(s) in sequence:\n%2\n\nThis requires an internet connection. Time depends on package size (tensorflow may take several minutes). Start now?",
    "DIAG_RECHECK": "Re-check",
    "DIAG_CLOSE_LOCKED": "Installing, please wait",
    "DIAG_PATH_INVALID": "⚠ No usable Python found (current setting: %1). Click \"Browse...\" to select python.exe, or install Python 3.10+ and add it to PATH.",
    "DIAG_PATH_RESOLVED": "Resolved to %1 (%2)",
    "DIAG_SUMMARY": "Install finished: %1 succeeded, %2 failed",
    "DIAG_LOCK_SWITCH": "Python environment is installing; cannot switch language/theme right now",
    "DIAG_LOCK_RELOAD": "Python environment is installing; cannot reload right now",
    "DIAG_INSTALL_STALLED": "No new output for %1s. It may be compiling or the network is slow, please wait...",
    "DIAG_CLOSE_WARN_INSTALLING": "Python environment installation is in progress. Closing the window will stop the install.",
    "DIAG_INSTALL_NO_PYTHON": "Please set a valid Python path before installing packages.",
    "MSG_CLOSE": "Close",

    // Update messages
    "MSG_CHECKING_UPDATE": "Checking for updates...",
    "MSG_UPDATE_LATEST": "Already up to date (%1)",
    "MSG_UPDATE_AVAILABLE": "New version available (%1)",
    "MSG_UPDATE_LATEST_TOOLTIP": "You are using the latest version (%1)",
    "MSG_UPDATE_AVAILABLE_TOOLTIP": "New version available (%1). Click to download.",

    // Dialogs & Messages
    "MSG_SAVE_CONFIRM": "Do you want to save changes to the current project?",
    "MSG_SWITCH_CONFIRM": "Switching modes will clear the workspace and start a new project. Are you sure you want to switch to %1 mode?",
    "MSG_SAVE": "Save",
    "MSG_DONT_SAVE": "Don't Save",
    "MSG_OK": "OK",
    "MSG_CANCEL": "Cancel",
    "MSG_SELECT_PATH": "Select Path",
    "MSG_SELECT_PORT": "Please select a serial port first!",
    "MSG_PYSERIAL_MISSING": "pyserial module not found. Please run 'pip install pyserial' to enable hardware deployment.",
    "MSG_DEPLOYING_MCU": "Deploying code to MCU (%1)...",
    "MSG_DEPLOY_UPLOADING": "Uploading, do not disconnect USB...",
    "MSG_DEPLOY_COMPLETED": "Upload completed, you can disconnect USB.",
    "MSG_UPDATE_LATEST": "You are already using the latest version.",
    "MSG_PYTHON_NOT_FOUND": "Could not execute Python (Current: %1). Please specify the correct python.exe path.",
    "MSG_PYTHON_UPDATED": "Python path updated: %1",
    "MSG_RECOVER_BACKUP": "Unsaved changes detected. Do you want to recover them?",
    "MSG_RECOVER_IGNORE": "Ignore and start new project",
    "MSG_READ_ONLY_ALERT": "This file is already open in another window and will be loaded in Read-Only mode. Use 'Save As' to make changes.",
    "MSG_READ_ONLY_HINT": "This file is open in another window (Read-Only).",
    "MSG_RESET_FIRMWARE_CONFIRM": "Resetting firmware will clear all content on the MCU. Please ensure the MCU is in BOOTSEL / Flashing mode.\nContinue?",
    "MSG_ASK_CLEAR_CODE": "Do you want to clear the code (main.py) on the MCU after burning?",
    "MSG_SELECT_MCU_MODEL": "Please select your MCU model:",
    "MSG_BOARD_MISMATCH": "The declared board (%1) does not match the detected board (%2). Upload anyway?",
    "MSG_FIRMWARE_BURN_SUCCESS": "Firmware burned successfully! The MCU will restart.",
    "MSG_FIRMWARE_BURN_FAILED": "Burning failed: ",
    "MSG_SETUP_STABLE_CONFIRM": "This will write boot.py to MCU to enable Stable Mode.\n\n[Effect]: Windows will become Read-Only for this drive (preventing damage), and Cocoya will upload code via Serial.\n[Escape]: To restore Windows write access later, hold \"GP20 button (Button 1)\" while plugging in the USB cable.\n\nAre you sure you want to continue?",

    "MSG_ERASE_FS_CONFIRM": "WARNING: This will force stop the program and ERASE ALL USER FILES (main.py, etc.) on the MCU. This cannot be undone! Continue?",
    "MSG_NO_TRAINING_RESULT": "No training results yet. Please run training first.",
    "MSG_RELOAD_HOME_CONFIRM": "Reloading will return to the Startup Home; unsaved changes will be lost. Continue?",
    "MSG_TRAINING_RESULT_TITLE": "Training Results",
    "MSG_TRAINING_RESULT_PROJECT": "Project Name",
    "MSG_TRAINING_RESULT_ACCURACY": "Validation Accuracy",
    "MSG_TRAINING_RESULT_EPOCHS": "Epochs",
    "MSG_TRAINING_RESULT_MODEL_DIR": "Model Directory",
    "MSG_OPEN_MODEL_FOLDER": "Open Model Folder",
    "MSG_TRAINING_RESULT_CLOSE": "Close",
    "MSG_TRAINING_COMPLETE_LOCAL": "--- Training complete: %1 ---",
    "MSG_TRAINING_COMPLETE_REMOTE": "--- Remote training complete: %1 ---",
    
    // Syntax (Basic)
    "PY_DEF": "def",
    "PY_RETURN": "return",
    "PY_GLOBAL": "global",
    "PY_LOCAL": "local"
  });
})(Blockly);
