(function (Blockly) {
  Blockly.Msg = Blockly.Msg || {};
  Object.assign(Blockly.Msg, {
    // 基礎 UI
    "BKY_HELP_HINT": "右鍵點擊查看說明",
    "BKY_SAVE_SUCCESS": "儲存成功！",
    "BKY_NEW_VARIABLE_HINT": "請輸入變數名稱（可使用逗號分隔建立多個）。\n注意：名稱不可由數字開頭，且不可包含底線以外的特殊符號。",
    "BKY_NEW_VARIABLE": "建立變數...",
    "BKY_RENAME_VARIABLE": "重新命名變數...",
    "BKY_DELETE_VARIABLE": "刪除變數 '%1'",
    "BKY_DELETE_VARIABLE_CONFIRMATION": "確定要刪除 %1 個 '%2' 變數嗎？",
    "BKY_VARIABLE_ALREADY_EXISTS": "已存在名為 '%1' 的變數。",
    "BKY_RENAME_VARIABLE_TITLE": "將所有 '%1' 變數重新命名為:",

    // 分類顏色 (Hex Palette)
    "COLOUR_STRUCTURE": "#585858",
    "COLOUR_LOGIC": "#b198de",
    "COLOUR_LOOPS": "#7fcd81",
    "COLOUR_MATH": "#5C68A6",
    "COLOUR_TEXT": "#6a8871",
    "COLOUR_TYPES": "#d1972b",
    "COLOUR_VARIABLES": "#ef9a9a",
    "COLOUR_FUNCTIONS": "#d22f73",
    "COLOUR_IO": "#34495e",
    "COLOUR_TIME": "#68a2a3",
    "COLOUR_CODING": "#585858",
    "COLOUR_AI": "#FF661A",
    "COLOUR_AI_BASIC": "#FF661A",
    "COLOUR_AI_DRAW": "#c2bc07",
    "COLOUR_AI_HAND": "#5bd211",
    "COLOUR_AI_FACE": "#01ad9c",
    "COLOUR_AI_POSE": "#1226a7",
    "COLOUR_HARDWARE": "#5c55a0",
    "COLOUR_MCU_CAMERA": "#db00ab",
    "COLOUR_HUSKYLENS": "#1f5a71",
    "COLOUR_MCU_CAR": "#ee5b56",
    "COLOUR_MCU_CAR_MOTOR": "#ee5b56",
    "COLOUR_MCU_CAR_SERVO": "#d40051",
    "COLOUR_MCU_CAR_MUSIC": "#de57ad",
    "COLOUR_MCU_CAR_LED": "#544eca",
    "COLOUR_MCU_CAR_SENSOR": "#b1b100",
    "COLOUR_MCU_CAR_BUTTON": "#0c8b03",
    
    // 分類名稱 (核心管理)
    "CAT_SEARCH": "搜尋積木",
    "CAT_STRUCTURE": "Structure",
    "CAT_IO": "IO",
    "CAT_TIME": "Time",
    "CAT_LOGIC": "Logic",
    "CAT_LOOPS": "Loops",
    "CAT_MATH": "Math",
    "CAT_TEXT": "Text",
    "CAT_TYPES": "Types",
    "CAT_CODING": "Coding",
    "CAT_VARIABLES": "Variables",
    "CAT_FUNCTIONS": "Functions",
    "CAT_AI": "AI 視覺",
    "CAT_AI_BASIC": "基礎操作",
    "CAT_AI_DRAW": "繪圖標註",
    "CAT_AI_HAND": "手勢偵測",
    "CAT_AI_FACE": "臉部網格",
    "CAT_AI_POSE": "姿勢偵測",
    "CAT_HARDWARE": "硬體控制",
    "CAT_MCU_CAMERA": "AI 相機",
    "CAT_HUSKYLENS": "HuskyLens",
    "CAT_MCU_CAR": "πCar 小車",

    // Types 分組標籤
    "TYPE_LBL_DEF": "建立資料結構",
    "TYPE_LBL_CAST": "型別轉換與檢查",
    "TYPE_LBL_OPS": "通用存取與判斷",
    "TYPE_LBL_METHODS": "進階操作 (清單/字典)",
    "TYPE_LBL_SORT": "排序功能",

    // 工具列與 UI 文字
    "TLB_NEW": "開新專案",
    "TLB_OPEN": "開啟專案",
    "TLB_SAVE": "儲存專案",
    "TLB_SAVE_AS": "另存專案",
    "TLB_SETTINGS": "設定",
    "TLB_SETTINGS_PYTHON_PATH": "設定 Python 路徑",
    "TLB_SETTINGS_SCROLL_OPTIONS": "啟用工作區自動平移 (需重啟)",
    "TLB_SETTINGS_FIRMWARE_GROUP": "韌體設定",
    "TLB_SETTINGS_ERASE_FS": "深度修復 (清空 MCU 檔案)",
    "TLB_SETTINGS_ERASE_FS_TOOLTIP": "強制停止無窮迴圈、清空 MCU 內部檔案。當程式卡死時使用。",
    "TLB_SETTINGS_RESET_FIRMWARE": "重置韌體 (燒錄系統)",
    "TLB_RUN": "執行程式",
    "TLB_RUN_PC": "執行 PC 端程式",
    "TLB_RUN_MCU": "上傳至 MCU",
    "TLB_UPDATE": "檢查更新",
    "TLB_STOP": "關閉編輯器",
    "TLB_STOP_PROGRAM": "停止執行",
    "TLB_TERMINAL": "開啟/關閉終端機",
    "TLB_TOGGLE_CODE": "開啟/關閉程式碼預覽",
    "TLB_PAUSE_SCROLL": "暫停自動捲動",
    "TLB_SERIAL_PORT": "序列埠",
    "TLB_SERIAL_REFRESH": "偵測序列埠",
    "TLB_SERIAL_CONNECT": "連接序列埠",
    "TLB_SERIAL_DISCONNECT": "斷開序列埠",
    "TLB_FILE_NEW": "未命名專案",
    "TLB_PYTHON_PREVIEW": "程式碼預覽",
    "TLB_MODE_PC": "💻 Python (PC)",
    "TLB_MODE_MCU": "📟 MicroPython (MCU)",
    "TLB_DIAGNOSE": "檢查 Python 套件需求",

    // 環境診斷
    "DIAG_TITLE": "環境診斷與安裝助手",
    "DIAG_LOADING": "正在偵測 Python 模組狀態...",
    "DIAG_CHECKING": "正在檢查...",
    "DIAG_INSTALLED": "● 已安裝",
    "DIAG_MISSING": "○ 未安裝",
    "DIAG_INSTALL_BTN": "安裝",
    "MSG_CLOSE": "關閉",

    // 更新檢查訊息
    "MSG_CHECKING_UPDATE": "正在檢查更新...",
    "MSG_UPDATE_LATEST": "目前已是最新版本 (%1)",
    "MSG_UPDATE_AVAILABLE": "有新版本可更新 (%1)",
    "MSG_UPDATE_LATEST_TOOLTIP": "目前已是最新版本 (%1)",
    "MSG_UPDATE_AVAILABLE_TOOLTIP": "有新版本可更新 (%1)，點擊前往下載",

    // 對話框與訊息
    "MSG_SAVE_CONFIRM": "您要儲存對目前專案的變更嗎？",
    "MSG_SWITCH_CONFIRM": "切換模式將會清除目前的工作區並建立新專案。確定要切換到 %1 模式嗎？",
    "MSG_SAVE": "儲存",
    "MSG_DONT_SAVE": "不儲存",
    "MSG_OK": "確定",
    "MSG_CANCEL": "取消",
    "MSG_SELECT_PATH": "選取路徑",
    "MSG_SELECT_PORT": "請先選擇序列埠！",
    "MSG_PYSERIAL_MISSING": "找不到 pyserial module，請先執行 'pip install pyserial' 以支援硬體部署。",
    "MSG_DEPLOYING_MCU": "正在部署程式至 MCU (%1)...",
    "MSG_DEPLOY_UPLOADING": "上傳中，請勿斷開 USB 連線...",
    "MSG_DEPLOY_COMPLETED": "上傳完畢，可斷開 USB 連線。",
    "MSG_PYTHON_NOT_FOUND": "無法執行 Python (目前設定: %1)。請指定正確的 python.exe 路徑。",
    "MSG_PYTHON_UPDATED": "Python 路徑已更新: %1",
    "MSG_RECOVER_BACKUP": "偵測到上次未儲存的變更，是否要恢復？",
    "MSG_RECOVER_IGNORE": "忽略並建立新專案",
    "MSG_RESET_FIRMWARE_CONFIRM": "重置韌體將清除 MCU 上的所有內容。請確保 MCU 已進入 BOOTSEL / 燒錄模式。\n是否繼續？",
    "MSG_ASK_CLEAR_CODE": "燒錄完成後，是否要清空 MCU 上的程式碼 (main.py)？",
    "MSG_SELECT_MCU_MODEL": "請選擇您的 MCU 型號：",
    "MSG_FIRMWARE_BURN_SUCCESS": "韌體燒錄成功！MCU 將重新啟動。",
    "MSG_FIRMWARE_BURN_FAILED": "燒錄失敗：",
    "MSG_RELOAD_TO_APPLY": "設定已儲存。請重新啟動編輯器以套用變更。",
    "MSG_ERASE_FS_CONFIRM": "【警告】：這將強制終止目前的程式並清空 MCU 內的所有使用者檔案（main.py 等），資料將消失且無法復原！\n\n確定要執行深度修復嗎？",

    // Python 核心關鍵字
    "PY_DEF": "def",
    "PY_RETURN": "return",
    "PY_GLOBAL": "global",
    "PY_LOCAL": "local"
  });
})(Blockly);
